# input paths
# ============================================================
# prompts file -- should be newline-delimited jsonl with each row having keys "text" and "meta"
# example:
# {"text": "Inorganic phosphate uptake in intact vacuoles isolated from suspension-cultured cells", "meta": {"pile_set_name": "PubMed Abstracts"}}
prompts_file = "data/text/pile_demo.jsonl"
# where to save patters -- both npz files of activations, and in step 1b png files of activation patterns
# structure is:
# `{patterns_dir}/{model_name}/prompts/{prompt_hash}/activations.npz`
# `{patterns_dir}/{model_name}/prompts/{prompt_hash}/L{layer_idx}/H{head_idx}/attn.png`
patterns_dir = "data/patterns"

# prompts processing
# ============================================================
# how many total prompts to use
prompts_n_samples = 128
# minimum chars per prompt
prompts_min_chars = 100
# maximum chars per prompt
prompts_max_chars = 1000

# data processing
# ============================================================
# which models to use (transformerlens names)
models = [
	# "pythia-410m",
	"pythia-1b",
	"gpt2-small",
	"gpt2-medium",
	# "gpt2-large",
	"meta-llama/Llama-3.2-1B",
	# "Llama-3.2-1B",
	# "Llama-3.2-1B-Instruct",
	"gemma-2b",
	"gemma-2-2b",
	# these are tiny and look weird
	# "pythia-14m",
	# "tiny-stories-1M",
]
# number of components for PCA decomposition of activation features
pca_n_components = 16

# computing
# ============================================================
# numbper of cpus to use for CPU tasks
n_proc = 12
# whether to force an overwrite of existing attention patterns
force_overwrite = false
# device to use for torch tensors -- generally "cpu", "cuda", or "mps"
# can be set thru cli with `--device`
device = "cuda:0"

# output paths
# ============================================================
# where to put the data of features extracted from the patterns
# see `DATA_FNAMES` for paths of data files relative to this directory
features_dir = "data/features"
# locations of data files relative to `features_dir`, probably don't modify this
# data_fnames = {} 

# plotting/logging
# ============================================================
# directory to save figures in
figures_dir = "data/figures"
# locations of figures relative to `figures_dir`, probably don't modify this
# figure_fnames {}

# verbosity level for logging
verbose = 99

# extra kwargs to pass to plotting functions. kind of messy
[plot_kwargs]
pca_all_dpi = 150

