name: Checks

on:
  workflow_dispatch:
  pull_request:
    branches: "*"
  push:
    branches:
      - main

jobs:
  checks:
    name: Run all checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Check dependencies are up to date
        run: make dep-check

      - name: Install dependencies
        run: make dep

      - name: Check formatting
        run: make format-check
        
      - name: Install playwright, fetch libs, other setup
        run: make am-setup PIPELINE_CFG_PATH=tests/pipeline_cfg_test.toml

      - name: Run tests
        run: make test

      - name: Run type checking
        run: make typing